name: dvd_rental
config-version: 2
version: 2.0
profile: 'dbt-postgres'
model-paths: ["models"]
macro-paths: ["macros"]

models:
  dvd_rental:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
      +schema: intermediate
    mart:
      +materialized: table 